### ISSUE TITLE
Created an account on website, can't add clients. 

### ISSUE THREAD

**Issue by bretto36** [canvasowl/ribbbon#10]
Clicking the now link or the add client button takes me back to the clients list page

**Comment by canvasowl** [comment]
Hello @bretto36 

I see that you're correct. This issue seems to be happening on Firefox. If you test it on Chrome it 
works correctly. I will try to get to this fix by today or tomorrow. Thank you so much for spotting this.

**Comment by bretto36** [comment]
Same cause as #11

**Comment by canvasowl** [comment]
This has been taken care of
