### ISSUE TITLE
Account Settings

### ISSUE THREAD

**Issue by bretto36** [canvasowl/ribbbon#11]
Can't click to get to other areas of settings page. I'd like to delete my account but there is no option

**Comment by canvasowl** [comment]
@bretto36 Can you please specify what browser and version you are using. I cannot replicate this 
bug you are referring to. Thanks

**Comment by bretto36** [comment]
Firefox 47 - Windows 8

Have tested in chrome and it is working

**Comment by bretto36** [comment]
Seems to be a JS error

ReferenceError: event is not defined

event.preventDefault();

Fix below: (Added event into function() part)

function megaMenuInit(){	
	$(".mega-menu .links a").click(function(event){		
		event.preventDefault();

		$(".mega-menu .links a").removeClass("active").addClass("inactive");
		$(this).removeClass("inactive").addClass("active");

		var id = "#" + $(this).attr("data-id");
		$(".mega-menu .content .item").hide();
		$(id).show();
	});
}

**Comment by canvasowl** [comment]
This has been taken care of

**Comment by ghanoumwael** [comment]
hii the function megaMenuInit() it exist for me as a call in show where find define it in js
