### ISSUE TITLE
"client.js>deleteClient" typo

### ISSUE THREAD

**Issue by rotorbit69** [canvasowl/ribbbon#12]
makePrompt(
            "Are you sure you want to delete the client: "+currentClient.name+"?",
            "By deleting this client you will loose all data associated with any project under this client",
            "**No now**", "Yes");

Should be "NOT NOW" 

amazing what a single "T" can imply ;)

great program - well done !

**Comment by canvasowl** [comment]
Aha thanks for that catch!

**Comment by canvasowl** [comment]
Issue has been updated
