### ISSUE TITLE
[suggestion] project file attachments 

### ISSUE THREAD

**Issue by breadlesscode** [canvasowl/ribbbon#17]
Hi guys,

first, nice job! I think project attachments would be a nice thing. 

Do you agree?

**Comment by canvasowl** [comment]
Yes this is a much needed feature. In fact prior to update 2.0 file uploads was part of Ribbbon but had been removed because I wanted a better implementation of it.

So yes file attachments is a feature that will be coming to Ribbbon.

**Comment by breadlesscode** [comment]
Great news thanks

**Comment by canvasowl** [comment]
No problem.

**Comment by canvasowl** [comment]
I will go ahead and close this is this is not an issue but a great suggestion. Thank you for input and your suggestion has been noted
