### ISSUE TITLE
Tag 2.2?

### ISSUE THREAD

**Issue by ssx** [canvasowl/ribbbon#18]
Hi,

Your website states that the current version is 2.2, but only the older 1.5 version has been tagged. Any chances of a new tag/release? HUD is currently not working on master, so a tagged working later version would be great.

**Comment by canvasowl** [comment]
Weird I thought I tagged it, will tag it soon. Also if you pull master again the fix for Hud page should be in place.

**Comment by canvasowl** [comment]
Tag 2.2 has been created
