### ISSUE TITLE
SQLSTATE[HY000] [2002] No such file or directory  

### ISSUE THREAD

**Issue by jjsquady** [canvasowl/ribbbon#22]
HI! I cloned the repo, run composer install and when I run artisan migrate... error :(

What happened? 

Thanks!

**Comment by canvasowl** [comment]
Will look into this, have not ran into this issue. May I ask how is your local server set up. Are you using WAMP or something similar?

**Comment by tekmor** [comment]
Change settings in `config/database.php` file. 

Set default database engine on line 29 (MySQL by default) : 
`'default' => env('DB_CONNECTION', 'mysql'),` 

Then configure your auth above line 47. eg for MySQL : 
```
'connections' => [
        'mysql' => [
             'driver'    => 'mysql',
            'host'      => env('DB_HOST', 'YOUR_DB_HOST'),
            'database'  => env('DB_DATABASE', 'YOUR_DATABASE_NAME'),
            'username'  => env('DB_USERNAME', 'YOUR_USERNAME'),
            'password'  => env('DB_PASSWORD', 'YOUR_PASSWORD'),
            'charset'   => 'utf8',
            'collation' => 'utf8_unicode_ci',
            'prefix'    => '',
            'strict'    => false,
        ],
    ],
```

**Comment by canvasowl** [comment]
@jjsquad The solution that @tekmor provided should do the trick.

**Comment by r15ch13** [comment]
Better Solution: copy `.env.example` to `.env` and change the database settings in `.env`

**Comment by breadlesscode** [comment]
I habe this in my .env-File
```
DB_HOST=host123.de
```

And laravel trys always to connect to localhost:
```
  [PDOException]                                                                                 
  SQLSTATE[HY000] [1045] Access denied for user 'user'@'localhost' (using password: YES)
```
I tryed: 
```
php56 artisan config:clear
```
And in my config/database.php I set it manualy 
```
 'host'      => 'host123.de',
```

But always localhost! Whats the problem?

**Comment by canvasowl** [comment]
@breadlesscode what is deleted?

**Comment by canvasowl** [comment]
Please do as @r15ch13 says. Will close this issue
