### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Riyazkhan1989** [canvasowl/ribbbon#23]
Hello Ribbon,
Thank you for providing this stuff, you are doing good job, love to see it.
Please use url() method for all link, Its not working if i click register or login page.
  e.g. 
<a href="{{url('/login')}}" class="btn btn-primary btn-line pull-right login">Login</a>

**Comment by canvasowl** [comment]
In what browser are you having this issue?

**Comment by r15ch13** [comment]
This happends if you use it in a directory like: `https://example.com/ribbbon`
So `/login` points to `https://example.com/login` instead of `https://example.com/ribbbon/login`

**Comment by Riyazkhan1989** [comment]
I checked it in Mozila.
