### ISSUE TITLE
always try to connect to localhost

### ISSUE THREAD

**Issue by breadlesscode** [canvasowl/ribbbon#28]
I have this in my .env-File
```
DB_HOST=host123.de
```

but laravel trys always to connect to localhost:
```
  [PDOException]                                                                                 
  SQLSTATE[HY000] [1045] Access denied for user 'user'@'localhost' (using password: YES)
```
I tryed: 
```
php artisan config:clear
```
and in my config/database.php I set it manualy 
```
 'host'      => 'host123.de',
```

But always localhost! Whats the problem?

**Comment by canvasowl** [comment]
These settings should be set in your .env file

**Comment by breadlesscode** [comment]
I know :D Laravel is my life.. 

But the hostname is always localhost for laravel. Its the first time I have this kind of problem.

**Comment by breadlesscode** [comment]
I thinks this is an laravel issue..
