### ISSUE TITLE
trying to register fails

### ISSUE THREAD

**Issue by jopi2016** [canvasowl/ribbbon#32]
Hi,

I cloned the repo and followed the installation steps. I can see the start site correctly but when I try to register I get the following error message:
Swift_RfcComplianceException in MailboxHeader.php line 347: Address in mailbox given [] does not comply with RFC 2822, 3.6.2.

    in MailboxHeader.php line 347
    at Swift_Mime_Headers_MailboxHeader->_assertValidAddress(false) in MailboxHeader.php line 263
    at Swift_Mime_Headers_MailboxHeader->normalizeMailboxes(array(false)) in MailboxHeader.php line 106
    at Swift_Mime_Headers_MailboxHeader->setNameAddresses(array(false)) in MailboxHeader.php line 63
    at Swift_Mime_Headers_MailboxHeader->setFieldBodyModel(array(false)) in SimpleMimeEntity.php line 592
    at Swift_Mime_SimpleMimeEntity->_setHeaderFieldModel('From', array(false)) in SimpleMessage.php line 219
    at Swift_Mime_SimpleMessage->setFrom(array(false), false) in Message.php line 37
    at Message->from(false, false) in Helpers.php line 50
...

**Comment by canvasowl** [comment]
Hmm first time I see this. Will investigate. Thanks for using Ribbbon

**Comment by jopi2016** [comment]
Amore,
k tal? Novedades?
Gracias a Dios me estoy acercando a las horas positivas - tengo nada ma´s 
menos 1 y cacho.

Se me olvidó orar por ustedes en la manana - ya lo hice en el carro. ;-)

Loving u guys soooooooo much!
Euer Jo

Mit freundlichen Grüßen/Best regards,

Joachim Mammele

Dipl. Ing.
Entwicklung Produkte/Product Development
Operating-and-Monitoring Systems (EP-OaM/PD-OaM)

Pilz GmbH & Co. KG, Sichere  Automation
Felix-Wankel-Straße 2, 73760 Ostfildern, Deutschland/Germany
Telefon +49  711 3409-225, Telefax +49  711 3409-9225
E-Mail: mailto:j.mammele@pilz.de, Internet: http://www.pilz.com



Von:    Jefry Cruz <notifications@github.com>
An:     canvasowl/ribbbon <ribbbon@noreply.github.com>
Kopie:  jopi2016 <j.mammele@pilz.de>, Author <author@noreply.github.com>
Datum:  09.12.2016 19:22
Betreff:        Re: [canvasowl/ribbbon] trying to register fails (#32)



Hmm first time I see this. Will investigate. Thanks for using Ribbbon
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.




Geschäftsführung: Renate Pilz, Susanne Kunschert, Thomas Pilz
Pilz GmbH & Co. KG, Sitz: Ostfildern, HRA 210 893, Amtsgericht Stuttgart
Kompl. Ges. Peter Pilz GmbH, Sitz: Ostfildern, HRB 210 612, Amtsgericht Stuttgart
Umsatzsteuer: ID-Nr. DE 145 355 773, WEEE-Reg.-Nr. DE 71636849

This email is intended solely for the use of the named address(es). Any unauthorised disclosure, copying or distribution of these confidential information contained therein, or the taking of any action based on it, is prohibited. The sender disclaims any liability for the integrity of this email. Legally binding declarations must be in written form.

Umweltschutz liegt uns am Herzen! - Bitte denken Sie an unsere Umwelt, bevor Sie diese E-Mail drucken.
We do care about the environment! - Please consider the environment before printing this e-mail.

**Comment by canvasowl** [comment]
You may need to set your Mailgnun api keys

**Comment by abdul-rehman-2050** [comment]
I faced the same issue, the user will get registered but not with email verification. 
If want to solve this issue then have to add own mail ID. 
I think the instructions should be mentioned in Read me installation guide.

**Comment by abdul-rehman-2050** [comment]
I such case, registration is done. You can try to login. even with this error.

**Comment by cringer** [comment]
Did you configure all your mail information in the .env file?

```
MAIL_DRIVER=smtp
MAIL_HOST=mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null

MAIL_FROM=someone@yourdomain.com
MAIL_FROM_NAME="Project Administrator"

ADMIN_EMAIL=youremail@youremail.com
```

**Comment by vesper8** [comment]
I was able to get past this error after adding my mailgun settings:

```
MAIL_DRIVER=mailgun
MAILGUN_DOMAIN=xxx.com
MAILGUN_SECRET=key-xxx

MAIL_FROM=support@xxx.com
MAIL_FROM_NAME="xxx"

ADMIN_EMAIL=xxx@gmail.com
```

However I still got an error GuzzleHttp\Client not found

After installing

composer require guzzlehttp/guzzle

Then I was able to sign up without error

Although oddly, I never did receive a confirmation email.. and I checked my spam folder
