### ISSUE TITLE
RuntimeException in compiled.php line 7082: 

### ISSUE THREAD

**Issue by abdul-rehman-2050** [canvasowl/ribbbon#34]
No supported encrypter found. The cipher and / or key length are invalid.

I cloned project from repo to my htdocs folder in xampp installation
I run command composer install 
and then migrated but got this error
could you please help?

**Comment by abdul-rehman-2050** [comment]
I just modified .env file and php artisan key:generate 
this solves the problem and now I have functional clone on my local host 
thank buddy realy appreciate this

**Comment by canvasowl** [comment]
Can you make a pull request with these changes so that others can have the fix. Thank you.

**Comment by abdul-rehman-2050** [comment]
I am little bit unaware of pull request as I have never been done this before. I tried once but failed to make pull request I will soon get back to it.
