### ISSUE TITLE
Composer install

### ISSUE THREAD

**Issue by daniel14145** [canvasowl/ribbbon#39]
Hi,i have problem when use command
`
![1](https://user-images.githubusercontent.com/16451076/27706443-e3167386-5d11-11e7-8380-03cd8f3ea15b.png)
![2](https://user-images.githubusercontent.com/16451076/27706444-e319f038-5d11-11e7-9dfa-5b31131f009a.png)

daniel@Juger:/volume1/web/projekty$ composer install
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - laravel/framework v5.1.10 requires jeremeamia/superclosure ~2.0 -> satisfiable by jeremeamia/SuperClosure[2.0.0, 2.1.0, 2.2.0, 2.3.0].
    - laravel/framework v5.1.11 requires jeremeamia/superclosure ~2.0 -> satisfiable by jeremeamia/SuperClosure[2.0.0, 2.1.0, 2.2.0, 2.3.0].
    - laravel/framework v5.1.12 requires jeremeamia/superclosure ~2.0 -> satisfiable by jeremeamia/SuperClosure[2.0.0, 2.1.0, 2.2.0, 2.3.0].
    - laravel/framework v5.1.13 requires jeremeamia/superclosure ~2.0 -> satisfiable by jeremeamia/SuperClosure[2.0.0, 2.1.0, 2.2.0, 2.3.0].
    - laravel/framework v5.1.14 requires jeremeamia/superclosure ~2.0 -> satisfiable by jeremeamia/SuperClosure[2.0.0, 2.1.0, 2.2.0, 2.3.0].
    - laravel/framework v5.1.15 requires jeremeamia/superclosure ~2.0 -> satisfiable by jeremeamia/SuperClosure[2.0.0, 2.1.0, 2.2.0, 2.3.0].
    - laravel/framework v5.1.16 requires jeremeamia/superclosure ~2.0 -> satisfiable by jeremeamia/SuperClosure[2.0.0, 2.1.0, 2.2.0, 2.3.0].
    - laravel/framework v5.1.17 requires jeremeamia/superclosure ~2.0 -> satisfiable by jeremeamia/SuperClosure[2.0.0, 2.1.0, 2.2.0, 2.3.0].
    - laravel/framework v5.1.18 requires jeremeamia/superclosure ~2.0 -> satisfiable by jeremeamia/SuperClosure[2.0.0, 2.1.0, 2.2.0, 2.3.0].
    - laravel/framework v5.1.19 requires jeremeamia/superclosure ~2.0 -> satisfiable by jeremeamia/SuperClosure[2.0.0, 2.1.0, 2.2.0, 2.3.0].
    - laravel/framework v5.1.20 requires jeremeamia/superclosure ~2.0 -> satisfiable by jeremeamia/SuperClosure[2.0.0, 2.1.0, 2.2.0, 2.3.0].
    - laravel/framework v5.1.21 requires jeremeamia/superclosure ~2.0 -> satisfiable by jeremeamia/SuperClosure[2.0.0, 2.1.0, 2.2.0, 2.3.0].
    - laravel/framework v5.1.22 requires jeremeamia/superclosure ~2.0 -> satisfiable by jeremeamia/SuperClosure[2.0.0, 2.1.0, 2.2.0, 2.3.0].
    - laravel/framework v5.1.23 requires jeremeamia/superclosure ~2.0 -> satisfiable by jeremeamia/SuperClosure[2.0.0, 2.1.0, 2.2.0, 2.3.0].
    - laravel/framework v5.1.24 requires jeremeamia/superclosure ~2.0 -> satisfiable by jeremeamia/SuperClosure[2.0.0, 2.1.0, 2.2.0, 2.3.0].
    - laravel/framework v5.1.25 requires jeremeamia/superclosure ~2.0 -> satisfiable by jeremeamia/SuperClosure[2.0.0, 2.1.0, 2.2.0, 2.3.0].
    - laravel/framework v5.1.26 requires jeremeamia/superclosure ~2.0 -> satisfiable by jeremeamia/SuperClosure[2.0.0, 2.1.0, 2.2.0, 2.3.0].
    - laravel/framework v5.1.27 requires jeremeamia/superclosure ~2.0 -> satisfiable by jeremeamia/SuperClosure[2.0.0, 2.1.0, 2.2.0, 2.3.0].
    - laravel/framework v5.1.28 requires jeremeamia/superclosure ~2.0 -> satisfiable by jeremeamia/SuperClosure[2.0.0, 2.1.0, 2.2.0, 2.3.0].
    - laravel/framework v5.1.29 requires jeremeamia/superclosure ~2.0 -> satisfiable by jeremeamia/SuperClosure[2.0.0, 2.1.0, 2.2.0, 2.3.0].
    - laravel/framework v5.1.30 requires jeremeamia/superclosure ~2.0 -> satisfiable by jeremeamia/SuperClosure[2.0.0, 2.1.0, 2.2.0, 2.3.0].
    - laravel/framework v5.1.31 requires jeremeamia/superclosure ~2.0 -> satisfiable by jeremeamia/SuperClosure[2.0.0, 2.1.0, 2.2.0, 2.3.0].
    - laravel/framework v5.1.32 requires jeremeamia/superclosure ~2.0 -> satisfiable by jeremeamia/SuperClosure[2.0.0, 2.1.0, 2.2.0, 2.3.0].
    - laravel/framework v5.1.33 requires jeremeamia/superclosure ~2.0 -> satisfiable by jeremeamia/SuperClosure[2.0.0, 2.1.0, 2.2.0, 2.3.0].
    - laravel/framework v5.1.34 requires jeremeamia/superclosure ~2.0 -> satisfiable by jeremeamia/SuperClosure[2.0.0, 2.1.0, 2.2.0, 2.3.0].
    - laravel/framework v5.1.35 requires jeremeamia/superclosure ~2.0 -> satisfiable by jeremeamia/SuperClosure[2.0.0, 2.1.0, 2.2.0, 2.3.0].
    - laravel/framework v5.1.36 requires jeremeamia/superclosure ~2.0 -> satisfiable by jeremeamia/SuperClosure[2.0.0, 2.1.0, 2.2.0, 2.3.0].
    - laravel/framework v5.1.37 requires jeremeamia/superclosure ~2.0 -> satisfiable by jeremeamia/SuperClosure[2.0.0, 2.1.0, 2.2.0, 2.3.0].
    - laravel/framework v5.1.38 requires jeremeamia/superclosure ~2.0 -> satisfiable by jeremeamia/SuperClosure[2.0.0, 2.1.0, 2.2.0, 2.3.0].
    - laravel/framework v5.1.39 requires jeremeamia/superclosure ~2.0 -> satisfiable by jeremeamia/SuperClosure[2.0.0, 2.1.0, 2.2.0, 2.3.0].
    - laravel/framework v5.1.40 requires jeremeamia/superclosure ~2.0 -> satisfiable by jeremeamia/SuperClosure[2.0.0, 2.1.0, 2.2.0, 2.3.0].
    - laravel/framework v5.1.41 requires jeremeamia/superclosure ~2.0 -> satisfiable by jeremeamia/SuperClosure[2.0.0, 2.1.0, 2.2.0, 2.3.0].
    - laravel/framework v5.1.42 requires jeremeamia/superclosure ~2.0 -> satisfiable by jeremeamia/SuperClosure[2.0.0, 2.1.0, 2.2.0, 2.3.0].
    - laravel/framework v5.1.43 requires jeremeamia/superclosure ~2.0 -> satisfiable by jeremeamia/SuperClosure[2.0.0, 2.1.0, 2.2.0, 2.3.0].
    - laravel/framework v5.1.44 requires jeremeamia/superclosure ~2.0 -> satisfiable by jeremeamia/SuperClosure[2.0.0, 2.1.0, 2.2.0, 2.3.0].
    - laravel/framework v5.1.45 requires jeremeamia/superclosure ~2.0 -> satisfiable by jeremeamia/SuperClosure[2.0.0, 2.1.0, 2.2.0, 2.3.0].
    - laravel/framework v5.1.46 requires jeremeamia/superclosure ~2.0 -> satisfiable by jeremeamia/SuperClosure[2.0.0, 2.1.0, 2.2.0, 2.3.0].
    - laravel/framework v5.1.7 requires jeremeamia/superclosure ~2.0 -> satisfiable by jeremeamia/SuperClosure[2.0.0, 2.1.0, 2.2.0, 2.3.0].
    - laravel/framework v5.1.8 requires jeremeamia/superclosure ~2.0 -> satisfiable by jeremeamia/SuperClosure[2.0.0, 2.1.0, 2.2.0, 2.3.0].
    - laravel/framework v5.1.9 requires jeremeamia/superclosure ~2.0 -> satisfiable by jeremeamia/SuperClosure[2.0.0, 2.1.0, 2.2.0, 2.3.0].
    - laravel/framework v5.1.0 requires psy/psysh 0.4.* -> satisfiable by psy/psysh[v0.4.0, v0.4.1, v0.4.2, v0.4.3, v0.4.4].
    - laravel/framework v5.1.1 requires psy/psysh 0.4.* -> satisfiable by psy/psysh[v0.4.0, v0.4.1, v0.4.2, v0.4.3, v0.4.4].
    - laravel/framework v5.1.2 requires psy/psysh 0.4.* -> satisfiable by psy/psysh[v0.4.0, v0.4.1, v0.4.2, v0.4.3, v0.4.4].
    - laravel/framework v5.1.3 requires psy/psysh 0.4.* -> satisfiable by psy/psysh[v0.4.0, v0.4.1, v0.4.2, v0.4.3, v0.4.4].
    - laravel/framework v5.1.4 requires psy/psysh 0.4.* -> satisfiable by psy/psysh[v0.4.0, v0.4.1, v0.4.2, v0.4.3, v0.4.4].
    - laravel/framework v5.1.5 requires psy/psysh 0.4.* -> satisfiable by psy/psysh[v0.4.0, v0.4.1, v0.4.2, v0.4.3, v0.4.4].
    - laravel/framework v5.1.6 requires psy/psysh 0.4.* -> satisfiable by psy/psysh[v0.4.0, v0.4.1, v0.4.2, v0.4.3, v0.4.4].
    - jeremeamia/SuperClosure 2.2.0 requires nikic/php-parser ^1.2|^2.0 -> satisfiable by nikic/php-parser[v1.2.0, v1.2.1, v1.2.2, v1.3.0, v1.4.0, v1.4.1, v2.0.0, v2.0.1, v2.1.0, v2.1.1].
    - jeremeamia/SuperClosure 2.3.0 requires nikic/php-parser ^1.2|^2.0|^3.0 -> satisfiable by nikic/php-parser[v1.2.0, v1.2.1, v1.2.2, v1.3.0, v1.4.0, v1.4.1, v2.0.0, v2.0.1, v2.1.0, v2.1.1, v3.0.0, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5, v3.0.6].
    - jeremeamia/SuperClosure 2.0.0 requires nikic/php-parser ~1.0 -> satisfiable by nikic/php-parser[v1.0.0, v1.0.1, v1.0.2, v1.1.0, v1.2.0, v1.2.1, v1.2.2, v1.3.0, v1.4.0, v1.4.1].
    - jeremeamia/SuperClosure 2.1.0 requires nikic/php-parser ~1.0 -> satisfiable by nikic/php-parser[v1.0.0, v1.0.1, v1.0.2, v1.1.0, v1.2.0, v1.2.1, v1.2.2, v1.3.0, v1.4.0, v1.4.1].
    - psy/psysh v0.4.0 requires nikic/php-parser ~1.0 -> satisfiable by nikic/php-parser[v1.0.0, v1.0.1, v1.0.2, v1.1.0, v1.2.0, v1.2.1, v1.2.2, v1.3.0, v1.4.0, v1.4.1].
    - psy/psysh v0.4.1 requires nikic/php-parser ~1.0 -> satisfiable by nikic/php-parser[v1.0.0, v1.0.1, v1.0.2, v1.1.0, v1.2.0, v1.2.1, v1.2.2, v1.3.0, v1.4.0, v1.4.1].
    - psy/psysh v0.4.2 requires nikic/php-parser ~1.0 -> satisfiable by nikic/php-parser[v1.0.0, v1.0.1, v1.0.2, v1.1.0, v1.2.0, v1.2.1, v1.2.2, v1.3.0, v1.4.0, v1.4.1].
    - psy/psysh v0.4.3 requires nikic/php-parser ~1.0 -> satisfiable by nikic/php-parser[v1.0.0, v1.0.1, v1.0.2, v1.1.0, v1.2.0, v1.2.1, v1.2.2, v1.3.0, v1.4.0, v1.4.1].
    - psy/psysh v0.4.4 requires nikic/php-parser ~1.0 -> satisfiable by nikic/php-parser[v1.0.0, v1.0.1, v1.0.2, v1.1.0, v1.2.0, v1.2.1, v1.2.2, v1.3.0, v1.4.0, v1.4.1].
    - nikic/php-parser v3.0.6 requires ext-tokenizer * -> the requested PHP extension tokenizer is missing from your system.
    - nikic/php-parser v3.0.5 requires ext-tokenizer * -> the requested PHP extension tokenizer is missing from your system.
    - nikic/php-parser v3.0.4 requires ext-tokenizer * -> the requested PHP extension tokenizer is missing from your system.
    - nikic/php-parser v3.0.3 requires ext-tokenizer * -> the requested PHP extension tokenizer is missing from your system.
    - nikic/php-parser v3.0.2 requires ext-tokenizer * -> the requested PHP extension tokenizer is missing from your system.
    - nikic/php-parser v3.0.1 requires ext-tokenizer * -> the requested PHP extension tokenizer is missing from your system.
    - nikic/php-parser v3.0.0 requires ext-tokenizer * -> the requested PHP extension tokenizer is missing from your system.
    - nikic/php-parser v2.1.1 requires ext-tokenizer * -> the requested PHP extension tokenizer is missing from your system.
    - nikic/php-parser v2.1.0 requires ext-tokenizer * -> the requested PHP extension tokenizer is missing from your system.
    - nikic/php-parser v2.0.1 requires ext-tokenizer * -> the requested PHP extension tokenizer is missing from your system.
    - nikic/php-parser v2.0.0 requires ext-tokenizer * -> the requested PHP extension tokenizer is missing from your system.
    - nikic/php-parser v1.4.1 requires ext-tokenizer * -> the requested PHP extension tokenizer is missing from your system.
    - nikic/php-parser v1.4.0 requires ext-tokenizer * -> the requested PHP extension tokenizer is missing from your system.
    - nikic/php-parser v1.3.0 requires ext-tokenizer * -> the requested PHP extension tokenizer is missing from your system.
    - nikic/php-parser v1.2.2 requires ext-tokenizer * -> the requested PHP extension tokenizer is missing from your system.
    - nikic/php-parser v1.2.1 requires ext-tokenizer * -> the requested PHP extension tokenizer is missing from your system.
    - nikic/php-parser v1.2.0 requires ext-tokenizer * -> the requested PHP extension tokenizer is missing from your system.
    - nikic/php-parser v1.1.0 requires ext-tokenizer * -> the requested PHP extension tokenizer is missing from your system.
    - nikic/php-parser v1.0.2 requires ext-tokenizer * -> the requested PHP extension tokenizer is missing from your system.
    - nikic/php-parser v1.0.1 requires ext-tokenizer * -> the requested PHP extension tokenizer is missing from your system.
    - nikic/php-parser v1.0.0 requires ext-tokenizer * -> the requested PHP extension tokenizer is missing from your system.
    - Installation request for laravel/framework 5.1.* -> satisfiable by laravel/framework[v5.1.0, v5.1.1, v5.1.10, v5.1.11, v5.1.12, v5.1.13, v5.1.14, v5.1.15, v5.1.16, v5.1.17, v5.1.18, v5.1.19, v5.1.2, v5.1.20, v5.1.21, v5.1.22, v5.1.23, v5.1.24, v5.1.25, v5.1.26, v5.1.27, v5.1.28, v5.1.29, v5.1.3, v5.1.30, v5.1.31, v5.1.32, v5.1.33, v5.1.34, v5.1.35, v5.1.36, v5.1.37, v5.1.38, v5.1.39, v5.1.4, v5.1.40, v5.1.41, v5.1.42, v5.1.43, v5.1.44, v5.1.45, v5.1.46, v5.1.5, v5.1.6, v5.1.7, v5.1.8, v5.1.9].

  To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php/php.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
`

**Comment by cringer** [comment]
Looks like you don't have the necessary PHP extensions configured correctly on your system.  This is because Ribbon utilized the Laravel framework. If i'm not mistaken you need the php-xml (or php7.0-xml) extension installed.  You didn't state which version of php you're running.

**Comment by canvasowl** [comment]
@cringer thanks for all your feedback on issues.
