### ISSUE TITLE
ribbbon sub directory installation 

### ISSUE THREAD

**Issue by GaneshKandu** [canvasowl/ribbbon#40]
Hi,

Trying to install Ribbbon in ```sub directory``` of web folder
ie. http://localhost/Ribbbon/public
but getting problem after installation

**Comment by canvasowl** [comment]
What is the issue you are getting?

**Comment by GaneshKandu** [comment]
jss and js files are not loading getting 404 error 
all the urls where pointing to root
```ie. http://localhost/Ribbbon/public/logout is http://localhost/logout```,
{{sometext}} is every where

**Comment by cringer** [comment]
Being that this is a Laravel app you should be serving from your public directory NOT from a subdirectory.  If configured correctly your site should be accessible at http://localhost.  This is what is going to cause your 404s

This is not an issue with ribbon, but an issue with your configuration.  If you need it to be in a subdirectory then you need to modify your configuration for this.  Just do a Google search on setting up Laravel in a subdirectory.
