### ISSUE TITLE
Seeder class not found when run db:seed at terminal

### ISSUE THREAD

**Issue by ridislam** [canvasowl/ribbbon#6]
hi,
when i tried to install this project Run "php artisan db:seed" this command showing error.

**Comment by canvasowl** [comment]
Hello Ridslam. Can you please tell me what is the error saying?

**Comment by ridislam** [comment]
in terminal that showing "seeder class not found in databaseSeeder.php"

**Comment by canvasowl** [comment]
Gotcha will get a fix up as soon as I can.

**Comment by canvasowl** [comment]
Ok this has been fixed, closing this ticket. ANd thnaks @ridislam for finding this issue.
